name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ext: .exe
          - os: ubuntu-22.04
            ext: ""
          - os: macos-latest
            ext: ""

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        if: matrix.os == 'windows-latest'
        run: go build -ldflags "-s -w" -o formseal-sync.exe ./cmd/formseal-sync

      - name: Build
        if: matrix.os != 'windows-latest'
        run: go build -ldflags "-s -w" -o formseal-sync ./cmd/formseal-sync

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            formseal-sync${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}